Smart ghost finished
ShalomPrinz/Pacman pull request #36
Opened 2019-03-27 20:23 UTC by ShalomPrinz

not the best, but for now it's ready

2019-03-29 12:22 UTC, danprinz requested changes

2019-03-29 12:22 UTC, danprinz commented on DeadGhost.java
> +			if ( nextLocation.equals(goal) )
this means that only if the ghost is one step next to the goal it will set the direction, isn't it?
you tested it only with one path available - "WD-R"
what about:
 "W----W"
 "R--D--"
 "W----W"

2019-03-29 12:22 UTC, danprinz commented on SmartGhost.java
> +		Direction forbiddenDirection = getOppositeDirection( getDirection() ), check;
don't mix variable declarations.
even if syntax is correct, it's a bad practice.

2019-03-29 12:22 UTC, danprinz commented on SmartGhost.java
> +		if (horizonalSpeed == 0) {
while it's very hard to follow your logic, I absolutely sure that you can write the very **same logic** more readable. 
and your logic is complex, please add some nice comment above to explain it

2019-04-01 18:46 UTC, ShalomPrinz commented on DeadGhost.java
> +			if ( nextLocation.equals(goal) )
5th test in DeadGhostTest: chooseTheOneStep - confirms one step path choosing, for all directions.

2019-05-17 11:05 UTC, closed without merging